-- MySQL Script generated by MySQL Workbench
-- 06/09/16 06:17:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laravel_i8n
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel_i8n
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel_i8n` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `laravel_i8n` ;

-- -----------------------------------------------------
-- Table `laravel_i8n`.`accueil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_i8n`.`accueil` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `titre_fr` VARCHAR(45) NOT NULL COMMENT '',
  `titre_nl` VARCHAR(45) NOT NULL COMMENT '',
  `description_fr` VARCHAR(255) NOT NULL COMMENT '',
  `description_nl` VARCHAR(45) NOT NULL COMMENT '',
  `image_fr` VARCHAR(255) NOT NULL COMMENT '',
  `image_nl` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
